### ISSUE TITLE
Morph border radius

### ISSUE THREAD

**Issue by julesbou** [Rich-Harris/ramjet#25]
When manually editing CSS styles on example page, border-radius property is not morphed

![capture d ecran 2015-05-04 a 18 33 09](https://cloud.githubusercontent.com/assets/328303/7457344/0d32ce46-f28c-11e4-8034-7c7e73cfa49e.png)
_screenshot_

**Comment by Rich-Harris** [comment]
Yes! Last night I created a new [border-radius branch](https://github.com/Rich-Harris/ramjet/tree/border-radius) to try and solve this issue. It's not totally straightforward - if the elements are the same shape, it works...

![border-radius](https://cloud.githubusercontent.com/assets/1162160/7458641/f7466bf6-f263-11e4-847c-c9f1c5e2152a.gif)

...but if they're a different shape, the transform stretches the corners so they don't overlap:

![border-radius2](https://cloud.githubusercontent.com/assets/1162160/7458649/0d7f61de-f264-11e4-8606-fd7eb57aef78.gif)

(It's subtle, but you can probably see what I'm talking about - the corners don't *quite* line up.) So we'll have to compensate for the transform when setting the border-radius (I didn't realise this until just now, but [you can use two radii for each corner](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius), which is exactly what we need to compensate for the 'stretch', which is great news because it means that this is in fact possible.)

Hopefully I'll get a chance to work on this soon.

Anyway, to your example: is the original border radius preserved, at least? It looks as though it isn't, but when I do the same thing locally I can see the blue circle beneath the translucent green square. Which is odd...

**Comment by Rich-Harris** [comment]
Right, I think I've got this sussed:

![brad](https://cloud.githubusercontent.com/assets/1162160/7465563/34eb8554-f2a0-11e4-8586-5a72cc311583.gif)

You can also see it in action on the [ramjet homepage](http://www.rich-harris.co.uk/ramjet/) (iOS grid example at the bottom). Released in 0.4.5

**Comment by julesbou** [comment]
works like a charm :)
