### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [Rich-Harris/ramjet#58]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by justintaddei** [comment]
@Rich-Harris It's been over a year now this issue has no response. I'm working on project that would benefit greatly from your work and would love to use ramjet however it doesn't seem wise to use an unmaintained project. As such I am going to create a new repo from a fork of ramjet and continue maintenance there. If you plan to continue work on ramjet please let me know and I will use your repo instead.

Thank you.

**Comment by justintaddei** [comment]
Stumbling across this more than a year after your issue was created, I think it is safe to assume that it is not maintained. This rather bummed me, and so I decided to create my own, maintained, element-morphing library. If you're interested, you can check it out here: https://github.com/justintaddei/illusory
